### ISSUE TITLE
Missing PBP breaks EPA Logic

### ISSUE THREAD

**Issue by ehess** [meysubb/cfbscrapR-MISC#1]
On line 719, of the CSV file of the 2018 starts the data for the Mississippi State-Louisiana game. Only 8 rows of information exist for this game in the file. From this point in the file on, the relationship of ep_after on play (n-1) and ep_before on play (n) no longer holds true for any play after this point in the file

**Comment by meysubb** [comment]
@ehess Thanks for opening the issue. I was able to fix this. I had to drop that game though since there was a lack of plays. 

Check it out now.

**Comment by ehess** [comment]
Awesome. Thanks for all your work on this project. Its a great resource!
